### ISSUE TITLE
Related work - move to `jobol/mustach`

### ISSUE THREAD

**Issue by wolfgangwalther** [PostgREST/plmustache#9]
Did you consider using https://gitlab.com/jobol/mustach instead of mutache-c? Seems to be actively maintained.. and from first glance seems to have implemented more of the spec?

At the same time, I found this:

https://github.com/RekGRpth/pg_mustach

Maybe this can be extended on?

**Comment by steve-chavez** [comment]
@wolfgangwalther Sure, done. I transferred that repo to my own account.
